module.exports = {
    BUILD_SCHEDULED: 'BUILD_SCHEDULED',
    BUILD_FAILED: 'BUILD_CANCELLED',
    DEPLOYMENT_PENDING: 'DEPLOYMENT_PENDING',
    DEPLOYMENT_SUCCESSFUL: 'DEPLOYMENT_SUCCESSFUL',
    DEPLOYMENT_FAILED: 'DEPLOYMENT_FAILED'
};
